/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames.geral;

import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author abelh
 */
public class CadUF extends javax.swing.JFrame {

    /**
     * Creates new form CadEstados
     */
    public CadUF() {
        initComponents();
        this.iniciaComponentes();
    }
    private void carregaPaises() {
        
        
        try {
            String SQL = "SELECT * FROM paises ORDER BY id asc;";
            Statement stmt = mysql.connector.connectMySQL.getConnection().createStatement();
            ResultSet rs = stmt.executeQuery(SQL);
            int a = -1;
            while (rs.next()) {
                txtIdPais.setText(rs.getString("id"));
                cbPais.addItem(rs.getString("nome"));
                a = a+1;
                cbPais.setSelectedIndex(a);
            }
            //aponta pais
            String SQL1 = "SELECT * FROM paises ORDER BY id asc limit 1;";
            Statement stmt1 = mysql.connector.connectMySQL.getConnection().createStatement();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro na Clausula de seleciona Pais: "+ ex.getMessage());
        }
        
    }
    private void iniciaComponentes() {
        this.carregaPaises();
        txtId.setText("0");
        txtNome.setText("");
        txtSigla.setText("");
        txtFusoHorario.setText("");
        txtCodIBGE.setText("");
    }
    private void insertUF()throws SQLException {
        
        String SQL = "INSERT INTO uf (nome, sigla, fuso_horario, cod_ibge,pais_id) VALUES (?,?,?,?,?)";
        PreparedStatement pst = mysql.connector.connectMySQL.getConnection().prepareStatement(SQL);
        pst.setString(1, txtNome.getText().toUpperCase());
        pst.setString(2, txtSigla.getText().toUpperCase());
        pst.setString(3, txtFusoHorario.getText());
        pst.setString(4, txtCodIBGE.getText());
        pst.setInt(5, Integer.parseInt(txtIdPais.getText()));
        pst.execute();
    }
    private void updateUF() throws SQLException {
        String SQL = "UPDATE uf SET nome = ?, sigla = ?,  fuso_horario = ?, cod_ibge = ? "
                + "WHERE id = ?";
        PreparedStatement pst = mysql.connector.connectMySQL.getConnection().prepareStatement(SQL);
        pst.setString(1, txtNome.getText().toUpperCase());
        pst.setString(2, txtSigla.getText().toUpperCase());
        pst.setString(3, txtFusoHorario.getText());
        pst.setString(4, txtCodIBGE.getText());
        pst.setInt(5, Integer.parseInt(txtId.getText()));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtSigla = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCodIBGE = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        btnDesfazer = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        txtIdPesquisa = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        AreaResultado = new javax.swing.JTextArea();
        btnFirst = new javax.swing.JButton();
        btnPrevious = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        txtFusoHorario = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        txtIdPais = new javax.swing.JTextField();
        cbPais = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ID");

        txtId.setEditable(false);

        jLabel2.setText("Nome");

        jLabel3.setText("Sigla");

        jLabel4.setText("Fuso Horário");

        jLabel5.setText("Cod. IBGE");

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnRemover.setText("Remover");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        btnDesfazer.setText("Desfazer");
        btnDesfazer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesfazerActionPerformed(evt);
            }
        });

        btnListar.setText("Listar Todos");

        jLabel6.setText("Pesquisar ID");

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        AreaResultado.setColumns(20);
        AreaResultado.setRows(5);
        jScrollPane1.setViewportView(AreaResultado);

        btnFirst.setText("First");

        btnPrevious.setText("Previous");

        btnNext.setText("Next");

        btnLast.setText("Last");
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });

        jLabel7.setText("País");

        cbPais.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbPaisItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnFirst)
                            .addComponent(jLabel7))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(txtIdPais, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbPais, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPrevious)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnNext)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnLast)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdPesquisa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPesquisar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnListar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtCodIBGE)
                                    .addComponent(txtSigla)
                                    .addComponent(txtFusoHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSalvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnRemover, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnDesfazer, javax.swing.GroupLayout.Alignment.TRAILING)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFirst)
                    .addComponent(btnPrevious)
                    .addComponent(btnNext)
                    .addComponent(btnLast))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtIdPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRemover)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDesfazer)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtIdPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnListar)
                                .addComponent(btnPesquisar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtSigla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtFusoHorario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCodIBGE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        // TODO add your handling code here:
        this.iniciaComponentes();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnDesfazerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesfazerActionPerformed
        // TODO add your handling code here:
        this.iniciaComponentes();
    }//GEN-LAST:event_btnDesfazerActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
//---- INICIO CLAUCULA PAIS ---
        int pais_id = 0;
        String pais_nome = String.valueOf(cbPais.getSelectedItem().toString());
        AreaResultado.append("\nPAIS SELECIONADO\n"+pais_nome);
        try {
            String SQL1 = "select paises.id from paises where paises.nome = '"+pais_nome+"'";
            Statement stmt = mysql.connector.connectMySQL.getConnection().createStatement();
            ResultSet rs = stmt.executeQuery(SQL1);
           
            if(rs.next()){
                pais_id = rs.getInt("ID");
                AreaResultado.append("\nID :"+rs.getInt("ID"));
                txtIdPais.setText(""+pais_id);
            }
           
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro na clausula de PAÍS." + ex.getMessage());
        }
        //---- FIM CLAUSULA PAIS ------
          if (txtNome.getText().trim().equals(""))      {
            JOptionPane.showMessageDialog(null, "Favor digite um nome para a UF!");
            txtNome.requestFocus();
            txtNome.setBackground(Color.red);
            return;
        } else if (txtSigla.getText().trim().equals(""))  {
            JOptionPane.showMessageDialog(null, "Favor digite uma sigla para a UF");
            txtSigla.requestFocus();
            txtSigla.setBackground(Color.red);
            return;
        } else if (txtFusoHorario.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Favor digite um fuso horário para a UF!");
            txtFusoHorario.requestFocus();
            txtFusoHorario.setBackground(Color.red);
            return;
        } else if (txtCodIBGE.getText().trim().equals(""))     {
            JOptionPane.showMessageDialog(null, "Favor digite um código IBGE para a UF!");
            txtCodIBGE.requestFocus();
            txtCodIBGE.setBackground(Color.red);
            return;
        }
        
        try {
            if (txtId.getText().equals("0")) { //INSERT
                insertUF();
                AreaResultado.append("Registro inserido com sucesso!"+"\n");
            } else { //UPDATE
                updateUF();
                AreaResultado.append("Registro atualizado com sucesso!"+"\n");
            }
            this.iniciaComponentes();
        } catch (SQLException mensagem) {
            JOptionPane.showMessageDialog(null, "ERRO SQL: "+mensagem.getMessage());
        }
        
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        // TODO add your handling code here:
        if (txtId.getText().equals("0")){
            JOptionPane.showMessageDialog(null, "Selecione um Registro");
            return;
        }
        if (JOptionPane.showConfirmDialog(null, "Remover?")!=0){
            return;
        }
        try {
                String SQL = "DELETE FROM uf WHERE id = ?";
                PreparedStatement pst = mysql.connector.connectMySQL.getConnection().prepareStatement(SQL);
                pst.setInt(1, Integer.parseInt(txtId.getText()));
                if (pst.executeUpdate()!=0){
                    JOptionPane.showMessageDialog(null, "Removido");
                }else{
                    JOptionPane.showMessageDialog(null, " Não Removido");
                }
                this.iniciaComponentes();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Erro: "+ex.getMessage());
            }
        
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        // TODO add your handling code here:
        try {
            String scriptSQL = ("SELECT * FROM uf WHERE id = "+Integer.parseInt(txtIdPesquisa.getText()));
            Statement stmt = mysql.connector.connectMySQL.getConnection().createStatement();
            ResultSet rs = stmt.executeQuery(scriptSQL);
            if (txtIdPesquisa.getText().trim().equals("")){
                JOptionPane.showMessageDialog(null, "Digite um código para ser pesquisado!");
            }
            if (rs.next()){
                txtId.setText(rs.getString("id"));
                txtNome.setText(rs.getString("nome"));
                txtSigla.setText(rs.getString("sigla"));
                txtFusoHorario.setText(rs.getString("fuso_horario"));
                txtCodIBGE.setText(rs.getString("cod_ibge"));
            } else {
                JOptionPane.showMessageDialog(null, "Código não localizado !");
                txtIdPesquisa.requestFocus();
            }
        }catch(SQLException ex){
            System.out.println("ERRO:"+ex.getMessage());
        }
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        // TODO add your handling code here:
        try{
            String scriptSQL = ("SELECT * FROM uf ORDER BY id ASC");
            Statement stmt = mysql.connector.connectMySQL.getConnection().createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_READ_ONLY);
            ResultSet rs = stmt.executeQuery(scriptSQL);

            if (rs.last()){
                txtId.setText(rs.getString("id"));
                txtNome.setText(rs.getString("nome"));
                txtSigla.setText(rs.getString("sigla"));
                txtFusoHorario.setText(rs.getString("fuso_horario"));
                txtCodIBGE.setText(rs.getString("cod_ibge"));
            } 
               
        }catch(SQLException ex){
            System.out.println("ERRO:"+ex.getMessage());
        }       
    }//GEN-LAST:event_btnLastActionPerformed

    private void cbPaisItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbPaisItemStateChanged
        // TODO add your handling code here:
        //---- INICIO CLAUCULA PAIS ---
        int pais_id = 0;
        String pais_nome = String.valueOf(cbPais.getSelectedItem().toString());
        AreaResultado.append("\nPAIS SELECIONADO\n"+pais_nome);
        try {
            String SQL1 = "select paises.id from paises where paises.nome = '"+pais_nome+"'";
            Statement stmt = mysql.connector.connectMySQL.getConnection().createStatement();
            ResultSet rs = stmt.executeQuery(SQL1);
           
            if(rs.next()){
                pais_id = rs.getInt("ID");
                AreaResultado.append("\nID :"+rs.getInt("ID"));
                txtIdPais.setText(""+pais_id);
            }
           
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro na clausula de PAÍS." + ex.getMessage());
        }
        //---- FIM CLAUSULA PAIS ------
    }//GEN-LAST:event_cbPaisItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadUF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadUF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadUF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadUF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadUF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AreaResultado;
    private javax.swing.JButton btnDesfazer;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JButton btnRemover;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cbPais;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtCodIBGE;
    private javax.swing.JFormattedTextField txtFusoHorario;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtIdPais;
    private javax.swing.JTextField txtIdPesquisa;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtSigla;
    // End of variables declaration//GEN-END:variables
}
